# Generated by Django 3.2.7 on 2022-03-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_brand_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image_large',
            field=models.ImageField(blank=True, upload_to='static/img/brands'),
        ),
    ]
