# Generated by Django 3.2.7 on 2022-03-14 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand', '0004_brand_image_large'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='facebook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='brand',
            name='instagram',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='brand',
            name='telegram',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='brand',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
