# Generated by Django 3.2.7 on 2022-01-31 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_reviewrating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria Variación',
                'verbose_name_plural': 'Categorias Variaciones ',
            },
        ),
        migrations.RemoveField(
            model_name='variation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='size',
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='store.variation_category'),
            preserve_default=False,
        ),
    ]
