# Generated by Django 3.2.7 on 2022-02-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220218_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
    ]
