# Generated by Django 3.2.7 on 2022-02-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220218_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='image_product',
            field=models.ImageField(blank=True, upload_to='static/img/store/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200.0, error_messages={'name': {'max_length': 'The price must be between 0 and 999999.99.'}}, help_text='Maximum 99999.99', max_digits=7, verbose_name='Regular price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/store/<django.db.models.fields.CharField>'),
        ),
    ]
