# Generated by Django 3.2.7 on 2022-02-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220220_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_topSelling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_trending',
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('sale', 'sale'), ('new', 'new'), ('hot', 'hot')], max_length=10, null=True, verbose_name='Etiqueta'),
        ),
    ]
