# Generated by Django 3.2.7 on 2022-02-23 17:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220223_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='variation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='cualquier cosa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variation',
            name='label',
            field=models.CharField(blank=True, choices=[('sale', 'sale'), ('new', 'new'), ('hot', 'hot')], max_length=10, null=True, verbose_name='Etiqueta'),
        ),
        migrations.RemoveField(
            model_name='variation',
            name='image',
        ),
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ManyToManyField(blank=True, max_length=255, null=True, to='store.Image'),
        ),
    ]
