# Generated by Django 3.2.7 on 2022-02-23 17:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220223_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Cualquier cosa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=models.ManyToManyField(blank=True, max_length=255, to='store.Image'),
        ),
    ]
