# Generated by Django 3.2.7 on 2022-03-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_variation_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
