# Generated by Django 3.2.7 on 2022-03-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_variation_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='ip',
        ),
    ]
