# Generated by Django 3.2.7 on 2022-03-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20220308_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(default='color', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='size',
            name='slug',
            field=models.SlugField(default='size', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
