# Generated by Django 3.2.7 on 2022-03-16 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20220315_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareproducts',
            name='variations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.variation'),
            preserve_default=False,
        ),
    ]
