# Generated by Django 3.2.7 on 2022-03-16 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_compareproducts_variations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompareProducts',
        ),
    ]
