# Generated by Django 3.2.7 on 2022-03-10 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_blog_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
