# Generated by Django 3.2.7 on 2022-03-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_visitor',
            field=models.BooleanField(default=False),
        ),
    ]
