# Generated by Django 3.2.7 on 2022-03-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_is_visitor_account_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_visitor',
            field=models.BooleanField(default=False),
        ),
    ]
