# Generated by Django 3.2.7 on 2022-03-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_account_is_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
