# Generated by Django 3.2.7 on 2022-03-16 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_account_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='token',
        ),
    ]
