# Generated by Django 3.2.7 on 2022-02-18 20:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_rename_pepe_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
