# Generated by Django 3.2.7 on 2022-03-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_large',
            field=models.ImageField(blank=True, upload_to='static/img/categories'),
        ),
    ]
