# Generated by Django 3.2.7 on 2022-01-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption1', models.CharField(max_length=100, verbose_name='Título 1')),
                ('caption2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título 2')),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='Size: 1920x570', upload_to='static/img/slides', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Es Activo')),
            ],
            options={
                'verbose_name': 'Diapositiva',
                'verbose_name_plural': 'Diapositivas',
            },
        ),
    ]
