# Generated by Django 3.2.7 on 2022-01-26 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('street_address', models.CharField(max_length=100, verbose_name='Calle')),
                ('apartment_address', models.CharField(max_length=100, verbose_name='Apartamento')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='País')),
                ('zip', models.CharField(max_length=100, verbose_name='Zip')),
                ('address_type', models.CharField(choices=[('B', 'Cuenta'), ('S', 'Dirección')], max_length=1, verbose_name='Tipo de Envío')),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dirección de Envío',
                'verbose_name_plural': 'Dirección de Envíos',
            },
        ),
    ]
