# Generated by Django 3.2.7 on 2022-03-04 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cartitem_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Producto agregado al carrito', 'verbose_name_plural': 'Productos agregados al carrito'},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='coupon',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
