# Generated by Django 3.2.7 on 2022-03-04 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20220304_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='Código')),
                ('amount', models.FloatField(verbose_name='Monto')),
            ],
            options={
                'verbose_name': 'Coupón',
                'verbose_name_plural': 'Coupón',
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.coupon', verbose_name='Cupón'),
        ),
    ]
