# Generated by Django 3.2.7 on 2022-01-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.BooleanField(choices=[('T', 'Transfermovil'), ('P', 'Pagar al Recoger')]),
        ),
    ]
