# Generated by Django 3.2.7 on 2022-01-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('D', 'Domicilio'), ('P', 'Pagar al Recoger')], default='Domicilio', max_length=10),
        ),
    ]
