# Generated by Django 3.2.7 on 2022-01-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=123213123, max_length=100),
            preserve_default=False,
        ),
    ]
