# Generated by Django 3.2.7 on 2022-01-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
    ]
