# Generated by Django 3.2.7 on 2022-03-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20220304_0046'),
        ('orders', '0012_alter_orderproduct_variations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='Código')),
                ('amount', models.FloatField(verbose_name='Monto')),
            ],
            options={
                'verbose_name': 'Coupón',
                'verbose_name_plural': 'Coupón',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='cart.CartItem'),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=260, error_messages={'name': {'max_length': 'The price must be between 0 and 999999.99.'}}, help_text='Maximum 99999.99', max_digits=7, verbose_name='Regular price'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.coupon', verbose_name='Cupón'),
        ),
    ]
