# Generated by Django 3.2.7 on 2022-03-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderproduct_total_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='total_paid',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 999999.99.'}}, help_text='Maximum 99999.99', max_digits=7, null=True, verbose_name='Regular price'),
        ),
    ]
