# Generated by Django 3.2.7 on 2022-03-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_rename_product_price_orderproduct_total_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='total_paid',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
