# Generated by Django 3.2.7 on 2022-03-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20220304_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='total_paid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
