# Generated by Django 3.2.7 on 2022-03-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='visitors',
        ),
    ]
