# Generated by Django 3.2.7 on 2022-03-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_order_order_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
